"""initial migrate

Revision ID: 97647cf0a64f
Revises: 
Create Date: 2020-08-07 11:07:31.636905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97647cf0a64f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('pwdhash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
